### ISSUE TITLE
Asking for the baseline code~

### ISSUE THREAD

**Issue by brandy012367** [RightBank/Semantics-preserved-POI-embedding#1]
I have notice that place2vec are used as baseline in your paper. So I have seeking for the original code in the reference, but the link is disappear. Could you please provide the baseline code ??  Thank you very much~

**Comment by RightBank** [comment]
Sorry for the late reply. You could find the codes of Place2Vec from the authors' repository https://github.com/BoYanSTKO/place2vec.
